version: "3"
services:
    grafana:
        image: grafana/grafana
        container_name: dc-grafana
        tty: true
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /data/grafana:/var/lib/grafana
